import {
  Activity,
  AlarmClock,
  Anchor,
  Aperture,
  Apple,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AtSign,
  Atom,
  Baby,
  Backpack,
  Bell,
  BookOpen,
  Brain,
  Briefcase,
  Bug,
  Calendar,
  Camera,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Clock,
  Cloud,
  Code2,
  Compass,
  Cpu,
  Database,
  Diamond,
  Download,
  FileText,
  Flag,
  Folder,
  Frown,
  Gift,
  Globe,
  GraduationCap,
  Hash,
  Heart,
  HelpCircle,
  House,
  Image,
  Key,
  Laptop,
  Lightbulb,
  Link,
  ListChecks,
  Lock,
  Mail,
  Map,
  MessageSquare,
  Mic,
  Minus,
  Monitor,
  Moon,
  Move,
  Music,
  Palette,
  Paperclip,
  Percent,
  Phone,
  Pin,
  Plane,
  Play,
  Plus,
  Presentation,
  Printer,
  RectangleHorizontal,
  Redo2,
  Rocket,
  RotateCcw,
  Shapes,
  Shield,
  ShoppingCart,
  Smile,
  Sparkles,
  Square,
  Star,
  Sun,
  Target,
  Triangle,
  Trophy,
  Umbrella,
  Undo2,
  Upload,
  User,
  Video,
  Wifi,
  Wrench,
  X,
  Zap,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import type { CanvasNodeShape } from '../formats/canvasFormat';

export interface ShapeOption {
  id: CanvasNodeShape;
  label: string;
}

export interface ShapeGroup {
  id: string;
  label: string;
  options: ShapeOption[];
}

export interface IconOption {
  id: string;
  label: string;
  Icon: LucideIcon;
  category: IconCategory;
}

export type IconCategory =
  | 'Basics'
  | 'Arrows'
  | 'Education'
  | 'Objects'
  | 'Status'
  | 'Media'
  | 'People'
  | 'Places'
  | 'Tech';

export const SHAPE_GROUPS: ShapeGroup[] = [
  {
    id: 'recent',
    label: 'Zuletzt verwendete Formen',
    options: [
      { id: 'rounded-rectangle', label: 'Rounded' },
      { id: 'rectangle', label: 'Rectangle' },
      { id: 'ellipse', label: 'Ellipse' },
      { id: 'diamond', label: 'Diamond' },
      { id: 'speech-bubble', label: 'Bubble' },
      { id: 'arrow-right', label: 'Arrow' },
      { id: 'cloud', label: 'Cloud' },
      { id: 'star', label: 'Star' },
    ],
  },
  {
    id: 'lines',
    label: 'Linien',
    options: [
      { id: 'line', label: 'Line' },
      { id: 'elbow-connector', label: 'Elbow' },
      { id: 'curved-connector', label: 'Curve' },
      { id: 'arrow-right', label: 'Right Arrow' },
      { id: 'arrow-left', label: 'Left Arrow' },
      { id: 'arrow-both', label: 'Both Arrow' },
      { id: 'bracket', label: 'Bracket' },
      { id: 'brace', label: 'Brace' },
    ],
  },
  {
    id: 'rectangles',
    label: 'Rechtecke',
    options: [
      { id: 'rectangle', label: 'Rectangle' },
      { id: 'rounded-rectangle', label: 'Rounded' },
      { id: 'square', label: 'Square' },
      { id: 'pill', label: 'Pill' },
      { id: 'document', label: 'Document' },
      { id: 'folder', label: 'Folder' },
    ],
  },
  {
    id: 'basic',
    label: 'Standardformen',
    options: [
      { id: 'ellipse', label: 'Ellipse' },
      { id: 'circle', label: 'Circle' },
      { id: 'triangle', label: 'Triangle' },
      { id: 'right-triangle', label: 'Right Triangle' },
      { id: 'diamond', label: 'Diamond' },
      { id: 'pentagon', label: 'Pentagon' },
      { id: 'hexagon', label: 'Hexagon' },
      { id: 'octagon', label: 'Octagon' },
      { id: 'parallelogram', label: 'Slant' },
      { id: 'trapezoid', label: 'Trapezoid' },
      { id: 'cylinder', label: 'Cylinder' },
      { id: 'cube', label: 'Cube' },
      { id: 'cloud', label: 'Cloud' },
      { id: 'callout', label: 'Callout' },
      { id: 'plus', label: 'Plus' },
      { id: 'multiply', label: 'Multiply' },
    ],
  },
  {
    id: 'block-arrows',
    label: 'Blockpfeile',
    options: [
      { id: 'arrow-right', label: 'Right Arrow' },
      { id: 'arrow-left', label: 'Left Arrow' },
      { id: 'arrow-up', label: 'Up Arrow' },
      { id: 'arrow-down', label: 'Down Arrow' },
      { id: 'arrow-both', label: 'Both Arrow' },
      { id: 'plus', label: 'Cross' },
      { id: 'ribbon', label: 'Ribbon' },
    ],
  },
  {
    id: 'equation',
    label: 'Formelformen',
    options: [
      { id: 'plus', label: 'Plus' },
      { id: 'minus', label: 'Minus' },
      { id: 'equals', label: 'Equals' },
      { id: 'multiply', label: 'Multiply' },
      { id: 'bracket', label: 'Bracket' },
      { id: 'brace', label: 'Brace' },
    ],
  },
  {
    id: 'flowchart',
    label: 'Flussdiagramm',
    options: [
      { id: 'flow-process', label: 'Process' },
      { id: 'flow-decision', label: 'Decision' },
      { id: 'flow-data', label: 'Data' },
      { id: 'flow-document', label: 'Document' },
      { id: 'flow-terminator', label: 'Terminator' },
      { id: 'flow-delay', label: 'Delay' },
      { id: 'flow-preparation', label: 'Preparation' },
      { id: 'flow-database', label: 'Database' },
    ],
  },
  {
    id: 'stars',
    label: 'Sterne und Banner',
    options: [
      { id: 'star', label: 'Star' },
      { id: 'burst', label: 'Burst' },
      { id: 'star-banner', label: 'Banner' },
      { id: 'ribbon', label: 'Ribbon' },
    ],
  },
  {
    id: 'legends',
    label: 'Legenden',
    options: [
      { id: 'speech-bubble', label: 'Speech Bubble' },
      { id: 'callout', label: 'Callout' },
      { id: 'rounded-rectangle', label: 'Label' },
      { id: 'document', label: 'Note' },
      { id: 'bracket', label: 'Bracket' },
      { id: 'brace', label: 'Brace' },
      { id: 'line', label: 'Leader Line' },
      { id: 'curved-connector', label: 'Curve' },
    ],
  },
  {
    id: 'interactive',
    label: 'Interaktive Schaltflächen',
    options: [
      { id: 'square', label: 'Button' },
      { id: 'rounded-rectangle', label: 'Rounded Button' },
      { id: 'circle', label: 'Circle Button' },
      { id: 'arrow-left', label: 'Previous' },
      { id: 'arrow-right', label: 'Next' },
      { id: 'plus', label: 'Add' },
      { id: 'minus', label: 'Remove' },
      { id: 'flow-process', label: 'Panel' },
    ],
  },
];

export const SHAPE_OPTIONS: ShapeOption[] = SHAPE_GROUPS.flatMap((group) => group.options)
  .filter((shape, index, shapes) => shapes.findIndex((candidate) => candidate.id === shape.id) === index);

export const ICON_OPTIONS: IconOption[] = [
  { id: 'sparkles', label: 'Sparkles', Icon: Sparkles, category: 'Basics' },
  { id: 'lightbulb', label: 'Idea', Icon: Lightbulb, category: 'Basics' },
  { id: 'star', label: 'Star', Icon: Star, category: 'Basics' },
  { id: 'heart', label: 'Heart', Icon: Heart, category: 'Basics' },
  { id: 'circle', label: 'Circle', Icon: Circle, category: 'Basics' },
  { id: 'square', label: 'Square', Icon: Square, category: 'Basics' },
  { id: 'diamond', label: 'Diamond', Icon: Diamond, category: 'Basics' },
  { id: 'triangle', label: 'Triangle', Icon: Triangle, category: 'Basics' },
  { id: 'rectangle', label: 'Rectangle', Icon: RectangleHorizontal, category: 'Basics' },
  { id: 'shapes', label: 'Shapes', Icon: Shapes, category: 'Basics' },
  { id: 'palette', label: 'Palette', Icon: Palette, category: 'Basics' },
  { id: 'plus', label: 'Plus', Icon: Plus, category: 'Basics' },
  { id: 'minus', label: 'Minus', Icon: Minus, category: 'Basics' },
  { id: 'x', label: 'X', Icon: X, category: 'Basics' },
  { id: 'hash', label: 'Hash', Icon: Hash, category: 'Basics' },
  { id: 'percent', label: 'Percent', Icon: Percent, category: 'Basics' },
  { id: 'arrow-right', label: 'Right', Icon: ArrowRight, category: 'Arrows' },
  { id: 'arrow-left', label: 'Left', Icon: ArrowLeft, category: 'Arrows' },
  { id: 'arrow-up', label: 'Up', Icon: ArrowUp, category: 'Arrows' },
  { id: 'arrow-down', label: 'Down', Icon: ArrowDown, category: 'Arrows' },
  { id: 'chevron-right', label: 'Chevron Right', Icon: ChevronRight, category: 'Arrows' },
  { id: 'chevron-left', label: 'Chevron Left', Icon: ChevronLeft, category: 'Arrows' },
  { id: 'chevron-up', label: 'Chevron Up', Icon: ChevronUp, category: 'Arrows' },
  { id: 'chevron-down', label: 'Chevron Down', Icon: ChevronDown, category: 'Arrows' },
  { id: 'move', label: 'Move', Icon: Move, category: 'Arrows' },
  { id: 'undo', label: 'Undo', Icon: Undo2, category: 'Arrows' },
  { id: 'redo', label: 'Redo', Icon: Redo2, category: 'Arrows' },
  { id: 'rotate', label: 'Rotate', Icon: RotateCcw, category: 'Arrows' },
  { id: 'book', label: 'Book', Icon: BookOpen, category: 'Education' },
  { id: 'graduation-cap', label: 'Study', Icon: GraduationCap, category: 'Education' },
  { id: 'brain', label: 'Brain', Icon: Brain, category: 'Education' },
  { id: 'atom', label: 'Atom', Icon: Atom, category: 'Education' },
  { id: 'map', label: 'Map', Icon: Map, category: 'Education' },
  { id: 'presentation', label: 'Slides', Icon: Presentation, category: 'Education' },
  { id: 'apple', label: 'Apple', Icon: Apple, category: 'Education' },
  { id: 'backpack', label: 'Backpack', Icon: Backpack, category: 'Education' },
  { id: 'file-text', label: 'File', Icon: FileText, category: 'Objects' },
  { id: 'briefcase', label: 'Case', Icon: Briefcase, category: 'Objects' },
  { id: 'folder', label: 'Folder', Icon: Folder, category: 'Objects' },
  { id: 'cloud', label: 'Cloud', Icon: Cloud, category: 'Objects' },
  { id: 'link', label: 'Link', Icon: Link, category: 'Objects' },
  { id: 'paperclip', label: 'Paperclip', Icon: Paperclip, category: 'Objects' },
  { id: 'message', label: 'Message', Icon: MessageSquare, category: 'Objects' },
  { id: 'pin', label: 'Pin', Icon: Pin, category: 'Objects' },
  { id: 'gift', label: 'Gift', Icon: Gift, category: 'Objects' },
  { id: 'target', label: 'Target', Icon: Target, category: 'Status' },
  { id: 'check', label: 'Check', Icon: CheckCircle2, category: 'Status' },
  { id: 'check-mark', label: 'Check Mark', Icon: Check, category: 'Status' },
  { id: 'activity', label: 'Activity', Icon: Activity, category: 'Status' },
  { id: 'clock', label: 'Clock', Icon: Clock, category: 'Status' },
  { id: 'bell', label: 'Bell', Icon: Bell, category: 'Status' },
  { id: 'flag', label: 'Flag', Icon: Flag, category: 'Status' },
  { id: 'zap', label: 'Zap', Icon: Zap, category: 'Status' },
  { id: 'help', label: 'Help', Icon: HelpCircle, category: 'Status' },
  { id: 'shield', label: 'Shield', Icon: Shield, category: 'Status' },
  { id: 'lock', label: 'Lock', Icon: Lock, category: 'Status' },
  { id: 'play', label: 'Play', Icon: Play, category: 'Media' },
  { id: 'image', label: 'Image', Icon: Image, category: 'Media' },
  { id: 'video', label: 'Video', Icon: Video, category: 'Media' },
  { id: 'music', label: 'Music', Icon: Music, category: 'Media' },
  { id: 'camera', label: 'Camera', Icon: Camera, category: 'Media' },
  { id: 'mic', label: 'Mic', Icon: Mic, category: 'Media' },
  { id: 'code', label: 'Code', Icon: Code2, category: 'Media' },
  { id: 'tasks', label: 'Tasks', Icon: ListChecks, category: 'Media' },
  { id: 'smile', label: 'Smile', Icon: Smile, category: 'People' },
  { id: 'frown', label: 'Frown', Icon: Frown, category: 'People' },
  { id: 'user', label: 'User', Icon: User, category: 'People' },
  { id: 'baby', label: 'Baby', Icon: Baby, category: 'People' },
  { id: 'heart-personal', label: 'Heart', Icon: Heart, category: 'People' },
  { id: 'house', label: 'House', Icon: House, category: 'Places' },
  { id: 'globe', label: 'Globe', Icon: Globe, category: 'Places' },
  { id: 'plane', label: 'Plane', Icon: Plane, category: 'Places' },
  { id: 'anchor', label: 'Anchor', Icon: Anchor, category: 'Places' },
  { id: 'compass', label: 'Compass', Icon: Compass, category: 'Places' },
  { id: 'umbrella', label: 'Umbrella', Icon: Umbrella, category: 'Places' },
  { id: 'sun', label: 'Sun', Icon: Sun, category: 'Places' },
  { id: 'moon', label: 'Moon', Icon: Moon, category: 'Places' },
  { id: 'rocket', label: 'Rocket', Icon: Rocket, category: 'Tech' },
  { id: 'cpu', label: 'CPU', Icon: Cpu, category: 'Tech' },
  { id: 'database', label: 'Database', Icon: Database, category: 'Tech' },
  { id: 'monitor', label: 'Monitor', Icon: Monitor, category: 'Tech' },
  { id: 'laptop', label: 'Laptop', Icon: Laptop, category: 'Tech' },
  { id: 'wifi', label: 'Wifi', Icon: Wifi, category: 'Tech' },
  { id: 'printer', label: 'Printer', Icon: Printer, category: 'Tech' },
  { id: 'download', label: 'Download', Icon: Download, category: 'Tech' },
  { id: 'upload', label: 'Upload', Icon: Upload, category: 'Tech' },
  { id: 'wrench', label: 'Wrench', Icon: Wrench, category: 'Tech' },
  { id: 'mail', label: 'Mail', Icon: Mail, category: 'Tech' },
  { id: 'phone', label: 'Phone', Icon: Phone, category: 'Tech' },
  { id: 'alarm-clock', label: 'Alarm', Icon: AlarmClock, category: 'Tech' },
  { id: 'calendar', label: 'Calendar', Icon: Calendar, category: 'Tech' },
  { id: 'key', label: 'Key', Icon: Key, category: 'Tech' },
  { id: 'aperture', label: 'Aperture', Icon: Aperture, category: 'Tech' },
  { id: 'bug', label: 'Bug', Icon: Bug, category: 'Tech' },
  { id: 'shopping-cart', label: 'Cart', Icon: ShoppingCart, category: 'Objects' },
  { id: 'trophy', label: 'Trophy', Icon: Trophy, category: 'Status' },
  { id: 'at-sign', label: 'At', Icon: AtSign, category: 'Basics' },
];

export const ICON_CATEGORIES: IconCategory[] = [
  'Basics',
  'Arrows',
  'Education',
  'Objects',
  'Status',
  'Media',
  'People',
  'Places',
  'Tech',
];

export function getIconOption(iconId: string | undefined): IconOption | undefined {
  return ICON_OPTIONS.find((option) => option.id === iconId);
}

export function getShapeOption(shapeId: CanvasNodeShape | undefined): ShapeOption | undefined {
  return SHAPE_OPTIONS.find((option) => option.id === shapeId);
}
