-- Seed data for IdeenHub MVP
-- 10 example WebApp entries

-- Insert sample tags
INSERT INTO public.tags (name) VALUES
  ('SaaS'),
  ('Productivity'),
  ('E-commerce'),
  ('Marketing'),
  ('Design'),
  ('Developer Tools'),
  ('Analytics'),
  ('AI/ML'),
  ('Finance'),
  ('Education')
ON CONFLICT (name) DO NOTHING;

-- Insert sample ideas
INSERT INTO public.ideas (
  title,
  slug,
  short_desc,
  long_desc,
  tags,
  screenshot_url,
  source_url,
  producthunt_id,
  launch_date,
  monthly_revenue_estimate,
  monthly_users_estimate,
  time_to_revenue_days,
  published
) VALUES
  (
    'Notion AI - Workspace Intelligence',
    'notion-ai-workspace-intelligence',
    'AI-powered workspace that helps teams collaborate smarter with intelligent automation and insights.',
    'Notion AI transforms how teams work by integrating AI directly into your workspace. It helps with writing, summarizing, brainstorming, and automating repetitive tasks. Teams report 30% time savings on documentation and planning.',
    '["SaaS", "Productivity", "AI/ML"]'::jsonb,
    'https://via.placeholder.com/1200x800/0ea5e9/ffffff?text=Notion+AI',
    'https://www.notion.so/product/ai',
    'ph123456',
    '2023-11-01',
    500000.00,
    5000000,
    90,
    true
  ),
  (
    'Stripe Tax - Automated Tax Compliance',
    'stripe-tax-automated-compliance',
    'Automatically calculate and collect sales tax, VAT, and GST in over 50 countries with Stripe Tax.',
    'Stripe Tax removes the complexity of tax compliance for businesses selling globally. It automatically determines tax rates, collects taxes, and generates reports for filing. Used by thousands of businesses to stay compliant.',
    '["SaaS", "Finance", "Developer Tools"]'::jsonb,
    'https://via.placeholder.com/1200x800/635bff/ffffff?text=Stripe+Tax',
    'https://stripe.com/tax',
    'ph123457',
    '2022-06-15',
    2000000.00,
    100000,
    60,
    true
  ),
  (
    'Figma Dev Mode - Design to Code',
    'figma-dev-mode-design-code',
    'Streamline the handoff from design to development with Dev Mode, built for developers.',
    'Figma Dev Mode provides developers with everything they need to translate designs into code. It includes specs, measurements, and code snippets. Reduces handoff time by 50% and improves design implementation accuracy.',
    '["Design", "Developer Tools", "SaaS"]'::jsonb,
    'https://via.placeholder.com/1200x800/a259ff/ffffff?text=Figma+Dev+Mode',
    'https://www.figma.com/dev-mode',
    'ph123458',
    '2023-06-20',
    15000000.00,
    2000000,
    120,
    true
  ),
  (
    'Vercel Analytics - Real User Monitoring',
    'vercel-analytics-real-user-monitoring',
    'Understand your web app performance with real user metrics, Core Web Vitals, and custom events.',
    'Vercel Analytics provides comprehensive insights into your application performance. Track Core Web Vitals, user sessions, and custom events. Helps teams identify and fix performance issues before they impact users.',
    '["Analytics", "Developer Tools", "SaaS"]'::jsonb,
    'https://via.placeholder.com/1200x800/000000/ffffff?text=Vercel+Analytics',
    'https://vercel.com/analytics',
    'ph123459',
    '2023-03-10',
    3000000.00,
    500000,
    45,
    true
  ),
  (
    'Shopify Markets - Global Commerce',
    'shopify-markets-global-commerce',
    'Sell internationally with localized experiences, multi-currency, and automated compliance.',
    'Shopify Markets enables merchants to expand globally with ease. It handles currency conversion, localized pricing, and international shipping. Merchants see 40% increase in international sales on average.',
    '["E-commerce", "SaaS", "Finance"]'::jsonb,
    'https://via.placeholder.com/1200x800/95bf47/ffffff?text=Shopify+Markets',
    'https://www.shopify.com/markets',
    'ph123460',
    '2021-09-01',
    50000000.00,
    10000000,
    180,
    true
  ),
  (
    'Linear - Issue Tracking for Teams',
    'linear-issue-tracking-teams',
    'The issue tracking tool you will enjoy using. Built for high-performance teams.',
    'Linear combines issue tracking, project management, and team collaboration in one beautiful interface. Used by teams at companies like Vercel, Stripe, and Figma. Reduces context switching and improves team velocity.',
    '["SaaS", "Productivity", "Developer Tools"]'::jsonb,
    'https://via.placeholder.com/1200x800/5e6ad2/ffffff?text=Linear',
    'https://linear.app',
    'ph123461',
    '2020-01-15',
    8000000.00,
    500000,
    90,
    true
  ),
  (
    'Midjourney - AI Image Generation',
    'midjourney-ai-image-generation',
    'Create stunning images from text descriptions using advanced AI technology.',
    'Midjourney is an AI-powered image generation tool that creates beautiful, artistic images from text prompts. Used by designers, marketers, and creators worldwide. Generates millions of images monthly.',
    '["AI/ML", "Design", "SaaS"]'::jsonb,
    'https://via.placeholder.com/1200x800/26a269/ffffff?text=Midjourney',
    'https://www.midjourney.com',
    'ph123462',
    '2022-07-12',
    25000000.00,
    15000000,
    30,
    true
  ),
  (
    'Loom - Async Video Communication',
    'loom-async-video-communication',
    'Record and share video messages of your screen, camera, or both. Faster than typing.',
    'Loom makes communication more personal and efficient through video. Teams use it for async standups, product demos, and feedback. Reduces meeting time by 30% and improves clarity of communication.',
    '["SaaS", "Productivity", "Education"]'::jsonb,
    'https://via.placeholder.com/1200x800/625df5/ffffff?text=Loom',
    'https://www.loom.com',
    'ph123463',
    '2016-01-01',
    15000000.00,
    20000000,
    365,
    true
  ),
  (
    'Resend - Email API for Developers',
    'resend-email-api-developers',
    'The email API for developers. Build, test, and send transactional emails at scale.',
    'Resend provides a modern email API that developers love. It offers great deliverability, beautiful templates, and simple integration. Used by thousands of companies to send millions of emails monthly.',
    '["Developer Tools", "SaaS", "Marketing"]'::jsonb,
    'https://via.placeholder.com/1200x800/ff6b6b/ffffff?text=Resend',
    'https://resend.com',
    NULL,
    '2023-01-10',
    500000.00,
    100000,
    60,
    false
  ),
  (
    'Cal.com - Open Source Scheduling',
    'cal-com-open-source-scheduling',
    'Open source scheduling infrastructure for everyone. Self-hosted or cloud.',
    'Cal.com is the open source alternative to Calendly. It offers scheduling, timezone handling, and integrations. Used by teams who want control over their scheduling infrastructure and data.',
    '["SaaS", "Productivity", "Open Source"]'::jsonb,
    'https://via.placeholder.com/1200x800/292929/ffffff?text=Cal.com',
    'https://cal.com',
    NULL,
    '2021-01-01',
    2000000.00,
    500000,
    120,
    false
  );

