# -*- coding: utf-8 -*-
import json

cases = []

# ============================================================
# CASE 1: FRANKREICH - Alexia Daval
# ============================================================
cases.append({
  "id": "fr-daval-2017",
  "land": "Frankreich",
  "famous": True,
  "title": "Die Maske des Witwers",
  "subtitle": "Der Mordfall Alexia Daval und die Inszenierung der Trauer",
  "file": "Cour d'assises de la Haute-Saône · Verfahren gegen Jonathann Daval",
  "place": "Gray-la-Ville, Département Haute-Saône, Frankreich",
  "date": "28. Oktober 2017",
  "year": 2017,
  "court": "Cour d'assises de la Haute-Saône et du Territoire de Belfort, Vesoul",
  "difficulty": 2,
  "duration": "mittel",
  "perpCount": 1,
  "teaser": "Ein Sonntagmorgen, eine Joggerin, die nicht zurückkehrt – und ein Ehemann, der vor laufenden Kameras weint und zur Suche aufruft. Doch je genauer man hinschaut, desto brüchiger wird sein Bild.",
  "tags": ["Gray-la-Ville", "Oktober 2017", "Erwürgen", "Falscher Trauer-Auftritt"],
  "victim": {
    "name": "Alexia Daval, geb. Fouillot (29)",
    "dossier": '''Alexia Daval, geborene Fouillot, wuchs in der Region um Gray im Département Haute-Saône auf. Mit ihrem Mann Jonathann, den sie seit der Jugend kannte, war sie seit Juli 2015 verheiratet. Das Paar hatte das Haus von Alexias Großeltern mütterlicherseits in Gray-la-Ville übernommen und gemeinsam renoviert. Beide verband die Leidenschaft für den Laufsport – kaum ein Wochenende verging ohne gemeinsames oder getrenntes Lauftraining. Alexia arbeitete in einer Bank und war für ihre Zuverlässigkeit bekannt. Nach außen wirkte die Ehe intakt und eingespielt. Im engeren Kreis war jedoch bekannt, dass das Paar sich seit Jahren ein Kind wünschte und diese Frage zunehmend zu Spannungen führte. Mehrere Quellen aus dem Umfeld sprachen später übereinstimmend von „lebhaften Spannungen", die die Beziehung in den Monaten vor Alexias Tod prägten. Für Außenstehende blieb davon jedoch wenig sichtbar: Kollegen und Nachbarn beschrieben Alexia als eine strukturierte, freundliche junge Frau, die ihren Alltag zwischen Arbeit, Familie und Sport fest im Griff hatte. Nichts in ihrem sichtbaren Leben deutete auf eine akute Bedrohung hin. Am Abend vor ihrem Verschwinden aß sie mit Jonathann bei ihren Eltern zu Abend – ein gewöhnlicher Sonntagabend in einer Familie, die sich regelmäßig traf und in der niemand ahnte, dass dies einer der letzten gemeinsamen Abende sein würde.''',
    "lastDay": '''Am Morgen des 28. Oktober 2017 soll Alexia gegen 9:30 Uhr das gemeinsame Haus in Gray-la-Ville verlassen haben, um eine ihrer gewohnten Laufrunden zu drehen. Sie trug Sportkleidung, hatte aber weder Telefon noch Ausweispapiere bei sich. Niemand aus der sonst belebten Nachbarschaft will sie an diesem Vormittag laufen gesehen haben – ein erster, zunächst unauffälliger Widerspruch. Gegen 12:25 Uhr alarmierte Jonathann Daval die Gendarmerie: Seine Frau sei nicht von ihrer Runde zurückgekehrt. Er gab an, den Vormittag über selbst nach ihr gesucht zu haben, mit dem Auto und zu Fuß, bevor er sich an die Behörden wandte. Ein Nachbar meldete später, in der Nacht zuvor – zwischen Freitag und Samstag, gegen 1:30 Uhr – ein Fahrzeug gehört zu haben, das über eine Metallplatte vor dem Haus der Davals gerollt sei. Noch am selben Abend organisierten Freunde und Familie eine erste Suchaktion, die in den folgenden Tagen zu einem der größten zivilen Sucheinsätze wurde, den die Region je gesehen hatte – mit hunderten Freiwilligen, die Wälder und Felder rund um Gray durchkämmten.''',
  },
  "intro": [
    "Ein Sonntagmorgen im Oktober, ein Waldweg am Rand von Gray-la-Ville, eine Joggerin, die nicht zurückkehrt. Was als tragisches Verschwinden beginnt, wird binnen weniger Tage zu einem der meistbeachteten Kriminalfälle Frankreichs – nicht wegen der Tat allein, sondern wegen des Mannes, der vor laufenden Kameras weint, zur Suche aufruft und tausende Menschen mobilisiert.",
    "Die Region Haute-Saône steht Kopf: Hunderte Freiwillige durchkämmen Wälder und Felder, die Presse berichtet landesweit. Im Zentrum der Aufmerksamkeit steht Jonathann Daval, der untröstliche Ehemann, dessen Auftritt bei einem stillen Trauermarsch minutiös von Kameras festgehalten wird. Doch parallel zur öffentlichen Anteilnahme beginnt eine zweite, stillere Ermittlung.",
    "Ein Nachbar, der ein Fahrzeug in der Nacht hört. Eine Metallplatte vor dem Haus. Kratzspuren, die mal so, mal anders erklärt werden. Der Fall Alexia Daval zeigt, wie eine sorgfältig inszenierte Fassade unter dem Druck forensischer Details Stück für Stück einstürzt. Folgen Sie den Spuren – von der ersten Vermisstenanzeige bis zur Urteilsverkündung in Vesoul.",
  ],
  "suspects": [
    {"id": "jonathann", "name": "Jonathann Daval", "init": "J", "role": "Ehemann des Opfers, meldete sie vermisst",
     "bio": '''Jonathann Daval, damals 34 Jahre alt, arbeitete als Informatik-Techniker in Gray und war wie Alexia sportbegeistert. In den Tagen nach ihrem Verschwinden inszenierte er sich als verzweifelter Ehemann, sprach vor Kameras und nahm am stillen Trauermarsch teil. Kollegen beschrieben ihn als „extrem freundlich" und unauffällig. Ermittler bemerkten früh Widersprüche zwischen seinen öffentlichen Auftritten und seinen Angaben zum Tagesablauf. Nach anfänglichem Leugnen widerrief er seine Aussagen mehrfach.'''},
    {"id": "nachbar_fahrzeug", "name": "Anonymer Hinweisgeber", "init": "?", "role": "Nachbar, der ein Fahrzeug in der Nacht hörte",
     "bio": '''Ein Nachbar des Ehepaars meldete den Ermittlern, in der Nacht vom 27. auf den 28. Oktober gegen 1:30 Uhr ein Fahrzeug gehört zu haben, das über eine Metallplatte vor dem Grundstück der Davals gefahren sei – ein Geräusch, das ihn geweckt habe und ihm eine präzise Uhrzeitangabe ermöglichte. Er selbst geriet nie unter Verdacht, seine Beobachtung wurde jedoch zu einem der wichtigsten Mosaiksteine der Ermittlung gegen den Ehemann.'''},
    {"id": "sexualstraftaeter", "name": "Unbekannter Sexualstraftäter", "init": "?", "role": "Frühe Theorie: Täter aus dem Umfeld",
     "bio": '''In den ersten Ermittlungswochen prüfte die Gendarmerie systematisch, ob ein in der Region bekannter Sexualstraftäter für den Angriff auf Alexia infrage kommen könnte – naheliegend angesichts der zunächst vermuteten Umstände einer Attacke auf offener Strecke. Nach Abgleich von Alibis und Bewegungsprofilen wurde diese Spur vollständig ausgeschlossen.'''},
    {"id": "geliebter", "name": "Unbekannter Liebhaber", "init": "?", "role": "Frühe Theorie: heimliche Affäre des Opfers",
     "bio": '''Parallel zur Prüfung eines möglichen Fremdtäters aus dem Umfeld untersuchten die Ermittler auch die Hypothese, Alexia könnte einen heimlichen Liebhaber gehabt haben, dessen Beziehung zu ihr eskaliert sei. Über 200 Personen aus dem Umfeld des Paares wurden dazu befragt. Auch diese Spur führte zu keinem belastbaren Ergebnis und wurde verworfen.'''},
    {"id": "phantom", "name": "Unbekannter Angreifer auf der Laufstrecke", "init": "?", "role": "Offizielle Ausgangsversion des Ehemanns",
     "bio": '''Die öffentliche Erzählung der ersten Tage – maßgeblich genährt durch Jonathann Davals eigene Schilderung gegenüber Presse und Ermittlern – stützte sich auf einen unbekannten Angreifer, der Alexia auf ihrer Laufstrecke überrascht habe. Diese Version prägte die große Suchaktion und den Trauermarsch. Fehlende Kampfspuren am vermuteten Tatort und spätere forensische Befunde ließen sie bald bröckeln.'''},
  ],
  "truth": {"taeter": ["jonathann"], "helfer": []},
  "policeTrack": [
    {"after": 1, "focus": "Vermisstenfall, Fremdtäter-Theorie", "note": "Nach der Vermisstenanzeige durch den Ehemann konzentriert sich die Suche auf die Laufstrecke; ein unbekannter Angreifer aus dem Wald gilt als naheliegendste Erklärung."},
    {"after": 2, "focus": "Systematischer Ausschluss von über 200 Personen", "note": "Die Theorien eines ortsansässigen Sexualstraftäters und eines heimlichen Liebhabers werden minutiös geprüft und schließlich verworfen."},
    {"after": 4, "focus": "Auffälligkeiten beim Ehemann", "note": "Der Hinweis des Nachbarn auf ein nächtliches Fahrzeug und Widersprüche in Jonathann Davals Tagesablauf rücken ihn erstmals in den Fokus."},
    {"after": 6, "focus": "Fahrzeug- und Spurenauswertung", "note": "Die kriminaltechnische Auswertung von Fahrzeug, Reifenspuren und biologischen Spuren liefert erste objektive Verbindungen zum Ehemann."},
    {"after": 7, "focus": "Gewahrsam und erstes Teilgeständnis", "note": "Nach Stunden der Befragung gesteht Jonathann Daval eine Beteiligung, relativiert sie zunächst aber wieder als Unfall."},
    {"after": 9, "focus": "Tatortbegehung und vollständiges Geständnis", "note": "Bei einer Rekonstruktion vor Ort bricht die letzte Verteidigungslinie; die endgültige Version deckt sich mit den forensischen Befunden."},
  ],
  "clues": [
    {"cat": "tatort", "label": "Fundort", "title": "Verstreute Gegenstände im Unterholz",
     "text": '''Tage nach Alexias Verschwinden entdecken Rettungskräfte am Rand eines Waldstücks bei Esmoulins, unweit von Gray-la-Ville, verstreute persönliche Gegenstände. Die Fundstelle liegt abseits der Bereiche, die Alexia nach Aussage von Trainingspartnern für ihre Läufe nutzte. Die Gendarmerie sperrt das Areal weiträumig ab und beginnt eine systematische Suche mit Spürhunden. Auffällig ist von Anfang an, dass sich am eigentlichen Fundort keine eindeutigen Kampfspuren auf offener Strecke nachweisen lassen – als sei dieser Ort nicht identisch mit dem tatsächlichen Ausgangspunkt des Geschehens. Diese Diskrepanz zwischen Fundstelle und vermutetem Tatgeschehen wird zu einem zentralen Rätsel der Ermittlung: Wurde hier tatsächlich gekämpft, oder wurde der Leichnam erst nachträglich hierher gebracht?''',
     "src": "Gendarmerie nationale / Wikipedia „Affaire Daval", "url": "https://fr.wikipedia.org/wiki/Affaire_Daval (abgerufen)"},
    {"cat": "forensik", "label": "Obduktion", "title": "Asphyxie und Schläge – kein Hinweis auf Sexualdelikt",
     "text": '''Die Autopsie von Alexias Leichnam liefert einen entscheidenden Befund: Sie wurde geschlagen und erstickt. Die Staatsanwältin von Besançon teilt Anfang November mit, dass Alexia Opfer von Gewalt und Schlägen wurde und erwürgt worden sei. Zu diesem Ermittlungsstand gebe es keine Hinweise auf ein Sexualdelikt. Der Leichnam weist zudem Brandspuren auf, die auf den Versuch hindeuten, Spuren zu vernichten. Für die Ermittler verschiebt sich damit das Bild: Statt eines flüchtigen Überfalls deutet die Kombination aus Schlägen, längerem Würgen und nachträglicher Brandlegung auf eine Tat im nahen Umfeld hin – verübt von jemandem, der Zeit und Gelegenheit hatte, den Leichnam zu verbergen und zu manipulieren.''',
     "src": "Staatsanwaltschaft Besançon, zitiert nach macommune.info", "url": "https://www.macommune.info/garde-a-vue-de-jonathann-daval-entre-soupcons-et-siderations-174921/ (abgerufen)"},
    {"cat": "zeuge", "label": "Der weiße Trauermarsch", "title": "Tränen vor laufenden Kameras",
     "text": '''Rund eine Woche nach dem Verschwinden ruft die Familie zu einer „marche blanche" auf, einem stillen Trauermarsch durch Gray, an dem zwischen 8.000 und 10.000 Menschen teilnehmen. Jonathann Daval hält vor Journalisten eine bewegende Ansprache und ruft zur Weiterführung der Suche auf. Sein Arbeitgeber beschreibt ihn später in der Presse als „extrem freundlich" und fragt rhetorisch, ob so jemand wirklich seine Frau getötet haben könne. Sein Anwalt Randall Schwerdorffer betont, sein Mandant sei „sehr gelassen" und bestreite die Vorwürfe vollständig. Diese sorgfältig aufrechterhaltene Fassade der Anteilnahme steht im Kontrast zu den Beobachtungen, die die Ermittler zur gleichen Zeit im Hintergrund sammeln – Beobachtungen, die niemand aus dem öffentlichen Bild ahnen lässt.''',
     "src": "macommune.info, Berichterstattung zum Trauermarsch", "url": "https://www.macommune.info/garde-a-vue-de-jonathann-daval-entre-soupcons-et-siderations-174921/ (abgerufen)"},
    {"cat": "zeuge", "label": "Ein Fahrzeug in der Nacht", "title": "Die Metallplatte vor dem Haus",
     "text": '''Ein Nachbar des Ehepaars berichtet den Gendarmen, in der Nacht vom Freitag auf Samstag gegen 1:30 Uhr ein Fahrzeug gehört zu haben, das über eine Metallplatte vor dem Grundstück der Davals gefahren sei – ein Geräusch, das ihn weckte und ihm eine präzise Zeitangabe ermöglichte. Die Gendarmen bestätigen tatsächlich das Vorhandensein einer solchen Platte vor dem Haus. Damit widerspricht diese Zeugenaussage der Darstellung, Jonathann Daval sei in dieser Nacht nicht mehr aus dem Haus gefahren. Zusammen mit anderen Ungereimtheiten im Tagesablauf wird der Ehemann verdächtigt, „über seinen Zeitplan gelogen" zu haben, wie es aus Ermittlerkreisen heißt.''',
     "src": "macommune.info, unter Berufung auf Le Point", "url": "https://www.macommune.info/garde-a-vue-de-jonathann-daval-entre-soupcons-et-siderations-174921/ (abgerufen)"},
    {"cat": "forensik", "label": "Fahrzeug- und Reifenspuren", "title": "Elektronische Daten widersprechen der offiziellen Version",
     "text": '''Das Firmenfahrzeug, das Jonathann Daval in jener Nacht genutzt haben soll, wird beschlagnahmt und an das Institut de recherche criminelle de la gendarmerie nationale (IRCGN) in Pontoise übergeben. Die Auswertung „elektronischer Elemente" im Fahrzeug bestätigt laut Ermittlerkreisen, dass der Wagen in der Nacht vom 27. auf den 28. Oktober gegen 1:30 Uhr tatsächlich bewegt wurde – zu einer Zeit, in der Jonathann laut eigener Aussage längst zu Hause war. Zudem werden Ähnlichkeiten zwischen den Profilen der Fahrzeugreifen und Reifenspuren festgestellt, die nahe der Fundstelle von Alexias Leichnam gesichert wurden. Diese technische Spur verbindet erstmals das Fahrzeug des Ehemanns direkt mit dem Gebiet, in dem später ihre sterblichen Überreste gefunden werden.''',
     "src": "macommune.info, unter Berufung auf Le Point", "url": "https://www.macommune.info/garde-a-vue-de-jonathann-daval-entre-soupcons-et-siderations-174921/ (abgerufen)"},
    {"cat": "dokument", "label": "Kratzer und Bissspuren", "title": "Eine Erklärung, die nicht mehr passt",
     "text": '''Bei seiner ersten Befragung als einfacher Zeuge erwähnt Jonathann Daval einen Streit mit Alexia am Vorabend ihres Verschwindens. Dieser Streit erkläre, so seine Darstellung, sichtbare Kratz- und mutmaßliche Bissspuren an seinen Armen. Am Abend des 27. Oktober habe das Paar noch gemeinsam bei Alexias Eltern zu Abend gegessen; nach der Heimkehr sei er nicht mehr ausgegangen, beteuert er in zwei Vernehmungen nach der Vermeldung des Verschwindens. Doch die Kombination aus frischen Verletzungsspuren an seinem Körper, dem Zeugenhinweis auf ein nächtliches Fahrzeug und der widerlegten Behauptung, das Haus nicht verlassen zu haben, lässt seine Version zunehmend brüchig erscheinen.''',
     "src": "macommune.info, Vernehmungsangaben", "url": "https://www.macommune.info/garde-a-vue-de-jonathann-daval-entre-soupcons-et-siderations-174921/ (abgerufen)"},
    {"cat": "verhoer", "label": "Garde à vue", "title": "48 Stunden Gewahrsam, ein erstes Wanken",
     "text": '''Am Montag, den 29. Januar 2018, um kurz nach 9 Uhr, wird Jonathann Daval in Garde à vue genommen – die erste förmliche Festnahme in dem Verfahren. Parallel durchsuchen Spezialisten der Spurensicherung sein Wohnhaus in Gray. Am Nachmittag wird er in die Räume der Gendarmerie an den „Forts de justice" in Besançon verlegt; die Garde à vue kann bis zu 48 Stunden dauern. Konfrontiert mit den ausgewerteten Fahrzeug- und Reifenspuren sowie der widerlegten Zeitleiste bricht seine bisherige Version zunehmend zusammen. Er räumt schließlich eine körperliche Auseinandersetzung mit Alexia ein, bezeichnet deren tödlichen Ausgang zunächst jedoch als Unfall im Streit.''',
     "src": "macommune.info, Prozessberichterstattung", "url": "https://www.macommune.info/garde-a-vue-de-jonathann-daval-entre-soupcons-et-siderations-174921/ (abgerufen)"},
    {"cat": "verhoer", "label": "Widerruf und erneutes Geständnis", "title": "Ein Hin und Her mit Ansage",
     "text": '''Nach seinem ersten Teilgeständnis widerruft Jonathann Daval Teile seiner Aussage erneut und kehrt zeitweise zu Ausflüchten zurück, bevor er unter dem Gewicht der Beweise wieder einlenkt. Dieses Muster – gestehen, relativieren, zurückrudern – zieht sich durch die gesamte Ermittlungsphase und später auch durch den Prozess. Es wird von der Anklage als Ausdruck seines Charakters gedeutet: ein Mann, der routiniert zwischen der Rolle des Opfers und kleinen, taktischen Zugeständnissen wechselt, der forensischen Beweislast aber letztlich nichts entgegenzusetzen hat.''',
     "src": "Prozessprotokolle, Cour d'assises de la Haute-Saône", "url": "https://fr.wikipedia.org/wiki/Affaire_Daval (abgerufen)"},
    {"cat": "prozess", "label": "Psychiatrisches Gutachten", "title": "Kontrollbedürfnis statt spontaner Affekt",
     "text": '''Im Rahmen der Ermittlungen und der späteren Hauptverhandlung erstellen psychiatrische Sachverständige Gutachten zur Persönlichkeit Jonathann Davals. Sie beschreiben einen Mann mit ausgeprägtem Bedürfnis nach Anerkennung und Kontrolle, der sich dem sportlichen und beruflichen Erfolg seiner Frau zunehmend nicht gewachsen gefühlt habe – vor dem Hintergrund jahrelanger Spannungen um den unerfüllten Kinderwunsch des Paares. Diese Einschätzung stützt die Anklagethese, wonach die Tat kein spontaner Unfall war, sondern Ausdruck einer eskalierenden Krise, die sich in einem Streit über die Zukunft der Beziehung entlud.''',
     "src": "Psychiatrisches Sachverständigengutachten, Prozessakte", "url": "https://fr.wikipedia.org/wiki/Affaire_Daval (abgerufen)"},
    {"cat": "prozess", "label": "Tatortbegehung", "title": "Das letzte, vollständige Geständnis",
     "text": '''Bei einer Tatortbegehung muss Jonathann Daval den Ablauf des Geschehens vor Ort rekonstruieren. Konfrontiert mit der physischen Umgebung und der Unmöglichkeit, seine bisherige Version aufrechtzuerhalten, liefert er eine detaillierte, in sich schlüssige Schilderung: ein eskalierender Streit im Haus, das Würgen im Affekt, der Transport der Leiche in den Wald und deren nachträgliches Anzünden. Vor der Cour d'assises im November 2020 bestätigt er diesen Kern der Ereignisse im Wesentlichen erneut. Die Anklage plädiert – gestützt auf Dauer und Intensität der Gewalteinwirkung laut Obduktion – für eine vorsätzliche Tötung statt eines bloßen Unfalls. Die Geschworenen folgen dieser Einschätzung und verurteilen ihn zu 25 Jahren Reclusion criminelle.''',
     "quote": "Wenn man jemanden so lange würgt, will man, dass er stirbt.", "src": "Prozessprotokoll, Cour d'assises de la Haute-Saône, Vesoul", "url": "https://fr.wikipedia.org/wiki/Affaire_Daval (abgerufen)"},
  ],
  "docs": [
    {"type": "polizeibericht", "title": "Vermisstenanzeige", "authority": "Gendarmerie nationale, Brigade de Gray", "ref": "PV-2017-1028-VG", "date": "28. Oktober 2017",
     "fields": [["Anzeigender", "Jonathann D."], ["Vermisste Person", "Alexia D., geb. Fouillot, 29 Jahre"], ["Uhrzeit der Anzeige", "12:25 Uhr"], ["Angegebene Aktivität", "Joggingrunde, ca. 9:30 Uhr losgelaufen"], ["Besonderheiten", "Kein Mobiltelefon mitgeführt, keine Zeugen der Laufrunde"]],
     "body": ["Der Anzeigende gibt an, seine Ehefrau habe das gemeinsame Haus gegen 9:30 Uhr zu einer gewohnten Laufrunde verlassen und sei bis zum Zeitpunkt der Anzeige nicht zurückgekehrt.", "Eine eigenständige Nachschau durch den Anzeigenden im Laufe des Vormittags habe keine Hinweise ergeben.", "Erste Befragung der Nachbarschaft ergibt keine Sichtung der Vermissten auf der üblichen Laufstrecke."],
     "stamp": "AMTLICH", "afterClue": 1},
    {"type": "gutachten", "title": "Vorläufige Mitteilung der Staatsanwaltschaft (Auszug)", "authority": "Parquet de Besançon", "ref": "PRB-2017-0447", "date": "Anfang November 2017",
     "fields": [["Auftraggeber", "Untersuchungsrichter, Tribunal de Besançon"], ["Untersuchungsgegenstand", "Sterbliche Überreste, aufgefunden Waldgebiet Esmoulins"], ["Zentrale Befunde", "Gewalteinwirkung, Schläge, Erwürgen"], ["Vorläufige Einschätzung", "Kein Hinweis auf Sexualdelikt zu diesem Ermittlungsstand"]],
     "body": ["Die festgestellten Verletzungen sprechen für eine Gewalttat mit Schlägen und anschließendem Erwürgen.", "Am Leichnam werden zusätzlich Brandspuren dokumentiert, die auf eine nachträgliche Manipulation der Auffindesituation hindeuten.", "Eine abschließende Beurteilung der Handlungsdauer wird für das weitere Verfahren als erheblich eingestuft."],
     "stamp": "VERTRAULICH", "afterClue": 2},
    {"type": "vernehmung", "title": "Vernehmungsprotokoll (Auszug, Garde à vue)", "authority": "Gendarmerie nationale, Forts de justice, Besançon", "ref": "PV-2018-0129-AUD", "date": "29.–30. Januar 2018",
     "fields": [["Vernommene Person", "Jonathann D., 34 Jahre"], ["Status zu Beginn", "Garde à vue, max. 48 Stunden"], ["Anwesender Verteidiger", "Me R. Schwerdorffer"]],
     "body": ["Der Vernommene bestreitet zunächst jede Beteiligung und verweist auf seine öffentlichen Suchaufrufe.", "Nach Vorhalt der ausgewerteten Fahrzeug- und Reifenspuren sowie der widerlegten Zeitleiste räumt er eine körperliche Auseinandersetzung ein, bezeichnet den Ausgang zunächst als unbeabsichtigt.", "Im weiteren Verlauf widerruft er Teile seiner Angaben, bevor er sie im Kern erneut bestätigt."],
     "stamp": "VERTRAULICH", "afterClue": 7},
  ],
  "pdfs": [],
  "links": [
    {"t": "Affaire Daval – Wikipédia (français)", "u": "https://fr.wikipedia.org/wiki/Affaire_Daval", "kind": "artikel"},
    {"t": "Murder of Alexia Daval – Wikipedia (English)", "u": "https://en.wikipedia.org/wiki/Murder_of_Alexia_Daval", "kind": "artikel"},
    {"t": "Garde à vue de Jonathann Daval : entre soupçons et sidérations", "u": "https://www.macommune.info/garde-a-vue-de-jonathann-daval-entre-soupcons-et-siderations-174921/", "kind": "artikel"},
    {"t": "Affaire Daval : plus de 800.000 euros réclamés par la famille d'Alexia", "u": "https://www.macommune.info/affaire-daval-plus-de-800-000-euros-reclames-par-la-famille-dalexia/", "kind": "artikel"},
  ],
  "solution": {
    "who": "Jonathann Daval (37)",
    "text": '''Nach über zwei Jahren Ermittlungsarbeit steht fest: Jonathann Daval hat seine Frau Alexia in der Nacht zum 28. Oktober 2017 im gemeinsamen Haus in Gray-la-Ville im Zuge eines eskalierenden Streits erwürgt. Anschließend transportierte er ihren Leichnam mit dem Auto in ein Waldgebiet bei Esmoulins und setzte ihn dort in Brand, um Spuren zu vernichten. Tagelang inszenierte er sich öffentlich als verzweifelt suchender Ehemann, sprach vor Kameras, nahm am stillen Trauermarsch mit tausenden Teilnehmern teil und ließ sich von seinem Arbeitgeber als „extrem freundlicher" Mann beschreiben. Was diese Fassade zum Einsturz brachte, waren keine spektakulären Enthüllungen, sondern eine Kette kleiner, unscheinbarer Widersprüche: ein Nachbar, der ein Fahrzeug in der Nacht hörte; elektronische Fahrzeugdaten, die eine nächtliche Fahrt belegten; Reifenspuren, die zum Fundort passten; Kratzspuren, deren Erklärung nicht mehr trug. Vor der Cour d'assises der Haute-Saône gestand er im November 2020 den Kern des Geschehens. Weder er noch die Staatsanwaltschaft legten gegen das Strafurteil Berufung ein – lediglich ein separates zivilrechtliches Verfahren um Schadensersatzforderungen der Familie Fouillot wurde in den Folgejahren noch weitergeführt.''',
    "quote": "Ich habe keine Erklärung dafür, was in mir vorging in diesem Moment.",
    "verdict": "Cour d'assises de la Haute-Saône et du Territoire de Belfort, Vesoul – 21. November 2020: 25 Jahre Reclusion criminelle",
    "status": "rechtskräftig seit Anfang Dezember 2020 (weder Verteidigung noch Staatsanwaltschaft legten Berufung ein)",
  },
})

# ============================================================
# CASE 2: SPANIEN - Laura Luelmo
# ============================================================
cases.append({
  "id": "es-luelmo-2018",
  "land": "Spanien",
  "famous": True,
  "title": "Der Nachbar von gegenüber",
  "subtitle": "Der Mordfall Laura Luelmo in einem Bergarbeiterdorf in Huelva",
  "file": "Audiencia Provincial de Huelva · Verfahren gegen Bernardo Montoya (Tribunal del Jurado)",
  "place": "El Campillo, Provinz Huelva, Andalusien, Spanien",
  "date": "12. Dezember 2018",
  "year": 2018,
  "court": "Audiencia Provincial de Huelva (Tribunal del Jurado)",
  "difficulty": 1,
  "duration": "kurz",
  "perpCount": 1,
  "teaser": "Eine junge Lehrerin kommt vom Einkaufen nicht nach Hause. Fünf Tage dauert die Suche in einem Dorf in der Sierra von Huelva – und endet an einem Ort, den ein Mann kennt, der nur wenige Meter entfernt wohnt.",
  "tags": ["El Campillo", "Dezember 2018", "Vorbestrafter Nachbar", "Sexualdelikt"],
  "victim": {
    "name": "Laura Luelmo (26)",
    "dossier": '''Laura Luelmo stammte aus der Provinz Zamora im Nordwesten Spaniens und hatte gerade erst ihr Lehramtsstudium hinter sich gebracht. Wenige Wochen vor ihrem Tod war sie nach Andalusien gezogen, um am Instituto der Ortschaft Nerva in der Provinz Huelva zu unterrichten, und hatte sich eine kleine Wohnung im benachbarten Dorf El Campillo genommen – mitten im ehemaligen Bergbaugebiet des Río Tinto. Kollegen und erste Schüler beschrieben sie als engagiert und aufgeschlossen; sie war erst wenige Wochen im Ort und kannte kaum jemanden über ihren neuen Arbeitsplatz hinaus. Freunde und Familie in Zamora hielten täglich Kontakt zu ihr, da der Umzug für sie ein aufregender, aber auch einsamer Neuanfang war. Sie hatte einen festen Freund, mit dem sie eine Fernbeziehung führte. Nachbarn in El Campillo nahmen sie kaum wahr – ein junges Gesicht in einem kleinen Ort, in dem sich sonst jeder kennt. Genau das sollte ihr zum Verhängnis werden: Ihr direkter Nachbar auf der anderen Straßenseite, ein Mann mit einer langen Vorstrafenliste, hatte sie in den Wochen zuvor offenbar beobachtet, ohne dass sie oder jemand in ihrem Umfeld davon wusste.''',
    "lastDay": '''Am Nachmittag des 12. Dezember 2018 erledigte Laura Luelmo gegen 17:30 Uhr Einkäufe in einem Supermarkt von El Campillo. Auf dem kurzen Weg zurück wurde sie von Bernardo Montoya abgefangen, der ihr gegenüber wohnte. Der Gerichtsentscheidung zufolge zerrte er sie mit Gewalt in sein Haus, verriegelte die Tür und schlug sie mit Fäusten und einem stumpfen Gegenstand nieder, fesselte ihre Hände auf dem Rücken und klebte ihr den Mund zu. Gegen 18:42 Uhr, „noch am Leben", verstaute er sie im Kofferraum seines Wagens. Zwischen 19:44 und 20:42 Uhr legte er ihren Körper in einem abgelegenen, schwer zugänglichen Gelände namens Las Mimbreras ab. Ihr Tod trat den Ermittlungen zufolge erst gegen 20:15 Uhr am folgenden Abend ein. Ihre Familie erstattete, nachdem sie unerreichbar blieb, Vermisstenanzeige.''',
  },
  "intro": [
    "Fünf Tage lang durchsuchen Freiwillige, Guardia Civil und Hubschrauber die Sierra um El Campillo, ein Bergarbeiterdorf in der Provinz Huelva. Laura Luelmo, eine 26-jährige Lehrerin, die erst wenige Wochen zuvor aus Zamora hierhergezogen ist, wird seit ihrem Einkauf am Nachmittag des 12. Dezember 2018 vermisst.",
    "Die erste Frage der Ermittler gilt dem, was in solchen Fällen meist zuerst geprüft wird: dem eigenen Umfeld der Vermissten – ihrem Freund, ihrer Familie. Doch Laura kannte in El Campillo kaum jemanden. Die eigentliche Gefahr, so stellt sich bald heraus, wohnte ihr die ganze Zeit gegenüber.",
    "Als am 17. Dezember ein Freiwilliger Kleidungsstücke in einem Gelände namens Las Mimbreras findet, wird aus der Vermisstensuche in Stunden ein Mordfall – und die Spur führt geradewegs zu einem Nachbarn mit einer Vorgeschichte, die er sorgfältig verborgen gehalten hatte.",
  ],
  "suspects": [
    {"id": "bernardo", "name": "Bernardo Montoya (50)", "init": "B", "role": "Nachbar auf der anderen Straßenseite",
     "bio": '''Bernardo Montoya wohnte Laura Luelmo direkt gegenüber und war ihr nach eigenen Angaben nie persönlich bekannt. Er war bereits 1997 rechtskräftig wegen Hausfriedensbruchs, Strafvereitelung und eines Tötungsdelikts verurteilt worden. Nachbarn beschrieben ihn als zurückgezogen. Dafür spricht seine unmittelbare Nähe zum Tatort und seine einschlägige Vorgeschichte, dagegen zunächst nur, dass er als Verdächtiger nicht sofort im Fokus stand, da er Laura offiziell nicht kannte.'''},
    {"id": "freund", "name": "Rolle: fester Freund des Opfers", "init": "F", "role": "Fernbeziehung, lebte nicht in Andalusien",
     "bio": '''Wie in Vermisstenfällen üblich, prüften die Ermittler zunächst das nähere persönliche Umfeld Laura Luelmos. Ihr Freund führte mit ihr eine Fernbeziehung und lebte nicht in der Provinz Huelva. Seine Kontaktdaten und Aufenthaltsorte am Tattag ließen sich rasch lückenlos klären, sodass diese Spur früh wieder verworfen wurde.'''},
    {"id": "unbekannter_pkw", "name": "Unbekannter Autofahrer", "init": "?", "role": "Frühe Theorie: Zufallsopfer auf offener Strecke",
     "bio": '''In den ersten Stunden der Suche hielten es die Ermittler für möglich, dass Laura auf dem kurzen Fußweg vom Supermarkt von einem unbekannten Fahrzeuginsassen angesprochen oder verschleppt worden war – eine naheliegende Theorie in einer dünn besiedelten Gegend mit wenig Videoüberwachung. Zeugenbefragungen in der gesamten Ortschaft ergaben jedoch keinerlei Hinweis auf ein fremdes Fahrzeug.'''},
    {"id": "vorbestrafter2", "name": "Rolle: weiterer polizeibekannter Mann im Ort", "init": "V", "role": "Sexualstraftäter-Register der Region",
     "bio": '''Da El Campillo ein kleiner Ort ist, glich die Guardia Civil das Register bekannter Sexual- und Gewaltstraftäter der Region routinemäßig ab. Ein weiterer, älterer Mann mit Vorstrafen aus einer Nachbargemeinde geriet kurzzeitig in den Fokus, konnte für den Nachmittag des 12. Dezember jedoch ein belastbares Alibi durch Familienangehörige vorweisen.'''},
    {"id": "exfreundin", "name": "Rolle: frühere Partnerin Bernardo Montoyas", "init": "E", "role": "von Montoya nach seiner Festnahme fälschlich beschuldigt",
     "bio": '''Nach seiner Festnahme behauptete Bernardo Montoya zeitweise, seine frühere Partnerin trage die Verantwortung für Lauras Tod. Gegen sie wurde nie ermittelt, da keinerlei Beweise oder Zeugenaussagen diese Behauptung stützten; die Ermittler werteten die Anschuldigung als Ablenkungsversuch. Sie wurde zu keinem Zeitpunkt angeklagt.'''},
  ],
  "truth": {"taeter": ["bernardo"], "helfer": []},
  "policeTrack": [
    {"after": 1, "focus": "Vermisstenfall, engstes Umfeld", "note": "Nach der Anzeige der Familie prüfen die Ermittler zunächst den festen Freund Lauras – Routine bei Vermisstenfällen mit jungen Frauen."},
    {"after": 2, "focus": "Zufallsopfer auf dem Nachhauseweg", "note": "Da Laura kaum jemanden im Ort kannte, wird ein zufälliger Angriff durch einen unbekannten Autofahrer für plausibel gehalten."},
    {"after": 3, "focus": "Abgleich mit dem Sexualstraftäter-Register", "note": "Die Guardia Civil überprüft polizeibekannte Männer der Region; ein weiterer Verdächtiger wird nach Alibi-Prüfung ausgeschlossen."},
    {"after": 4, "focus": "Der Nachbar gegenüber", "note": "Mit dem Fund der Kleidung in Las Mimbreras und ersten forensischen Spuren rückt Bernardo Montoya erstmals ins Zentrum der Ermittlungen."},
    {"after": 5, "focus": "Fall gilt als aufgeklärt", "note": "Nach Festnahme und Geständnis Montoyas gilt der Fall für die Ermittler als gelöst; seine spätere Schuldzuweisung an eine frühere Partnerin bleibt folgenlos."},
  ],
  "clues": [
    {"cat": "zeuge", "label": "Letzte Sichtung", "title": "Der Einkauf am Nachmittag",
     "text": '''Videoaufnahmen und Zeugenaussagen aus einem Supermarkt in El Campillo rekonstruieren Lauras letzte gesicherte Bewegungen: Gegen 17:30 Uhr am 12. Dezember 2018 kauft sie dort ein und macht sich anschließend zu Fuß auf den kurzen Heimweg. Danach verliert sich jede Spur. Ihr Mobiltelefon bleibt stumm, sie erscheint nicht zu keinem verabredeten Kontakt mit ihrer Familie in Zamora. Da sie erst wenige Wochen zuvor zugezogen war und kaum lokale Kontakte hatte, tappen die Ermittler zunächst im Dunkeln, welche Personen aus ihrem unmittelbaren Umfeld überhaupt infrage kommen – ein seltener Fall, in dem der Kreis der Verdächtigen zunächst nicht aus dem Bekanntenkreis des Opfers, sondern aus der Nachbarschaft eines Ortes stammen musste, den sie selbst kaum kannte.''',
     "src": "Telecinco, Rekonstruktion des Tatablaufs", "url": "https://www.telecinco.es/noticias/andalucia/20251207/bernardo-montoya-caso-laura-luelmo-crimen-huelva-condena_18_017766319.html"},
    {"cat": "tatort", "label": "Fund in Las Mimbreras", "title": "Kleidungsstücke in unwegsamem Gelände",
     "text": '''Fünf Tage nach ihrem Verschwinden, am 17. Dezember 2018, entdeckt ein Freiwilliger im Rahmen der organisierten Suche in einem als Las Mimbreras bekannten, schwer zugänglichen Gelände am Rand von El Campillo mehrere Kleidungsstücke. Die Guardia Civil weitet die Suche unmittelbar auf den unmittelbaren Umkreis aus und findet den Leichnam der jungen Lehrerin etwa 200 Meter vom Fundort der Kleidung entfernt, halb verborgen in einem Böschungs- und Gestrüppbereich. Die Wahl dieses abgelegenen, unwegsamen Ortes – fernab jeder Straße oder eines Wanderwegs – lässt die Ermittler früh vermuten, dass der Täter die Örtlichkeit genau kannte und gezielt so gewählt hatte, dass der Leichnam möglichst lange unentdeckt bleiben sollte.''',
     "src": "Telecinco, Rekonstruktion des Tatablaufs", "url": "https://www.telecinco.es/noticias/andalucia/20251207/bernardo-montoya-caso-laura-luelmo-crimen-huelva-condena_18_017766319.html"},
    {"cat": "forensik", "label": "Gerichtsmedizinischer Befund", "title": "Todeszeitpunkt fast 24 Stunden nach der Entführung",
     "text": '''Die Rechtsmedizin kommt zu einem besonders erschütternden Ergebnis: Laura Luelmo wurde nicht sofort getötet. Den Feststellungen des späteren Urteils zufolge war sie noch am Leben, als sie gegen 18:42 Uhr am 12. Dezember in den Kofferraum des Fahrzeugs verbracht und zwischen 19:44 und 20:42 Uhr in dem abgelegenen Gelände zurückgelassen wurde. Ihr Tod trat den Ermittlungen zufolge erst gegen 20:15 Uhr am Abend des 13. Dezember ein – fast einen ganzen Tag, nachdem sie dort mit auf dem Rücken gefesselten Händen abgelegt worden war. Diese Rekonstruktion verändert die rechtliche Bewertung erheblich: Der Täter handelte nicht im Affekt, sondern mit der erkennbaren Absicht, ein Auffinden zu verhindern, selbst um den Preis eines langsamen Todes des Opfers.''',
     "src": "Confilegal, Urteilsbericht", "url": "https://confilegal.com/20211210-prision-permanente-revisable-para-bernardo-montoya-por-el-asesinato-y-agresion-sexual-de-laura-luelmo/"},
    {"cat": "digital", "label": "Route des Fahrzeugs", "title": "Die Fahrt durch drei Gemeinden",
     "text": '''Die Rekonstruktion der Fahrzeugbewegungen ergibt, dass Bernardo Montoya nach der Tat mit seinem Wagen eine Route durch die Gemeindegebiete von Minas de Riotinto, Nerva und El Campillo fuhr, bevor er gegen 19:44 Uhr das abgelegene Gelände erreichte, in dem er Laura zurückließ. Diese Streckenführung – ein Umweg durch mehrere Ortschaften, statt direkt zum nächstgelegenen Versteck zu fahren – deutet den Ermittlern zufolge darauf hin, dass er gezielt nach einem möglichst unauffindbaren Ort suchte. Ihr Mobiltelefon nahm er mit, alle übrigen persönlichen Gegenstände ließ er zusammen mit dem Leichnam zurück.''',
     "src": "Confilegal, Urteilsbericht", "url": "https://confilegal.com/20211210-prision-permanente-revisable-para-bernardo-montoya-por-el-asesinato-y-agresion-sexual-de-laura-luelmo/"},
    {"cat": "verhoer", "label": "Festnahme und Geständnis", "title": "Ein Tag nach dem Leichenfund",
     "text": '''Bernardo Montoya wird bereits am 18. Dezember 2018 festgenommen, nur einen Tag nach dem Auffinden von Lauras Leichnam – seine unmittelbare Nähe zum Fundort und seine einschlägige Vorstrafe machen ihn rasch zum Hauptverdächtigen. In der ersten polizeilichen Vernehmung gesteht er das Verbrechen. Ab dem 4. April 2019 ändert er seine Aussage jedoch grundlegend: Fortan behauptet er, seine frühere Partnerin trage die Verantwortung für Lauras Tod. Diese neue Version bleibt ohne jede Stütze durch Beweise oder Zeugen; Montoya bleibt bis zum Prozess der einzige Angeklagte in dem Verfahren.''',
     "src": "Telecinco, Rekonstruktion des Tatablaufs", "url": "https://www.telecinco.es/noticias/andalucia/20251207/bernardo-montoya-caso-laura-luelmo-crimen-huelva-condena_18_017766319.html"},
    {"cat": "prozess", "label": "Urteil des Tribunal del Jurado", "title": "Prisión permanente revisable",
     "text": '''Am 9. Dezember 2021 verkündet die Audiencia Provincial de Huelva das Urteil Nr. 135/2021 auf Grundlage des Wahrspruchs eines Laienjury (Tribunal del Jurado). Vorsitzender Richter Florentino-Gregorio Ruíz Yamuza verhängt wegen Mordes mit dem erschwerenden Umstand der Rückfälligkeit die „prisión permanente revisable" – eine lebenslange, alle 25 bis 35 Jahre überprüfbare Freiheitsstrafe – sowie zusätzlich 17,5 Jahre Haft wegen Freiheitsberaubung in Tateinheit mit sexueller Nötigung, jeweils zuzüglich zehn Jahren überwachter Freiheit. Das Gericht wertet die vorangegangene Rückfälligkeitsverurteilung von 1997 wegen Hausfriedensbruchs, Strafvereitelung und eines Tötungsdelikts als Verschärfungsgrund. Montoya muss der Familie des Opfers zudem 400.000 Euro Entschädigung zahlen.''',
     "quote": "Er nutzte seine überlegene körperliche Kraft und äußerste Gewalt aus.", "src": "Confilegal, Urteilsbericht", "url": "https://confilegal.com/20211210-prision-permanente-revisable-para-bernardo-montoya-por-el-asesinato-y-agresion-sexual-de-laura-luelmo/"},
  ],
  "docs": [
    {"type": "polizeibericht", "title": "Vermisstenanzeige", "authority": "Guardia Civil, Puesto de El Campillo", "ref": "geschwärzt", "date": "13.12.2018",
     "fields": [["Vermisste Person", "Laura L., 26 Jahre, Lehrerin"], ["Letzter bekannter Aufenthalt", "Supermarkt El Campillo, ca. 17:30 Uhr"], ["Besonderheiten", "Kürzlich zugezogen, kaum lokale Kontakte"]],
     "body": ["Die Anzeigende gibt an, seit dem Nachmittag des Vortags keinen Kontakt zur Vermissten zu haben.", "Eine erste Befragung im Umfeld des Supermarkts bestätigt die Anwesenheit der Vermissten bis ca. 17:30 Uhr.", "Ein Sucheinsatz mit Unterstützung Freiwilliger wird eingeleitet."],
     "stamp": "AMTLICH", "afterClue": 1},
    {"type": "obduktion", "title": "Gerichtsmedizinischer Befund (Auszug)", "authority": "Instituto de Medicina Legal de Huelva", "ref": "geschwärzt", "date": "18.–19.12.2018",
     "fields": [["Auffindeort", "Las Mimbreras, Gemeinde El Campillo"], ["Fesselung", "Hände auf dem Rücken gefesselt"], ["Geschätzter Todeszeitpunkt", "ca. 20:15 Uhr, 13.12.2018"]],
     "body": ["Die Untersuchung ergibt stumpfe Gewalteinwirkung sowie Fesselungsspuren an beiden Handgelenken.", "Der Zeitpunkt des Todes liegt nach den Befunden deutlich nach dem Zeitpunkt des Verbringens an den Auffindeort.", "Hinweise auf ein Sexualdelikt werden gesichert und zur weiteren Auswertung an die Kriminaltechnik übergeben."],
     "stamp": "VERTRAULICH", "afterClue": 3},
    {"type": "vernehmung", "title": "Protokoll der ersten Vernehmung", "authority": "Guardia Civil, Kommissariat Huelva", "ref": "geschwärzt", "date": "18.12.2018",
     "fields": [["Beschuldigter", "Bernardo M., geb. 1968"], ["Vorstrafen", "Rechtskräftige Verurteilung von 1997 (Audiencia de Huelva)"], ["Status", "In Untersuchungshaft"]],
     "body": ["Der Beschuldigte legt in der ersten Vernehmung ein Geständnis zum Tatgeschehen ab.", "Angaben zum genauen Ablauf werden mit den gerichtsmedizinischen und kriminaltechnischen Befunden abgeglichen.", "Eine spätere Änderung der Aussage erfolgt erst mehrere Monate nach Verfahrensbeginn."],
     "stamp": "VERTRAULICH", "afterClue": 5},
  ],
  "pdfs": [],
  "links": [
    {"t": "Prisión permanente revisable para Bernardo Montoya (Confilegal)", "u": "https://confilegal.com/20211210-prision-permanente-revisable-para-bernardo-montoya-por-el-asesinato-y-agresion-sexual-de-laura-luelmo/", "kind": "artikel"},
    {"t": "Bernardo Montoya, el hombre que asesinó a Laura Luelmo (Telecinco)", "u": "https://www.telecinco.es/noticias/andalucia/20251207/bernardo-montoya-caso-laura-luelmo-crimen-huelva-condena_18_017766319.html", "kind": "artikel"},
  ],
  "solution": {
    "who": "Bernardo Montoya (53)",
    "text": '''Bernardo Montoya, ein 1968 geborener Mann mit einschlägiger Vorstrafe, überfiel am Nachmittag des 12. Dezember 2018 seine Nachbarin Laura Luelmo auf dem kurzen Weg vom Supermarkt zu ihrer Wohnung in El Campillo. Er zerrte sie in sein Haus, schlug und fesselte sie und vergewaltigte sie. Anschließend verbrachte er die noch lebende Frau in den Kofferraum seines Wagens, fuhr über die Gemeindegebiete von Minas de Riotinto und Nerva und legte sie schließlich in einem abgelegenen Gelände namens Las Mimbreras ab – mit der erklärten Absicht, dass ihr Leichnam nie gefunden würde. Sie starb dort, den gerichtsmedizinischen Feststellungen zufolge, erst fast 24 Stunden später. Fünf Tage nach ihrem Verschwinden fand ein Freiwilliger ihre Kleidung; die Guardia Civil entdeckte den Leichnam wenig später in unmittelbarer Nähe. Montoyas räumliche Nähe zum Tatort und seine Vorstrafe machten ihn binnen eines Tages zum Hauptverdächtigen; er gestand bei seiner ersten Vernehmung. Ein Wechsel seiner Aussage anderthalb Jahre später, mit dem er seine frühere Partnerin belastete, blieb folgenlos, da keinerlei Beweise sie stützten. Ein Geschworenengericht der Audiencia Provincial de Huelva befand ihn im Dezember 2021 für schuldig.''',
    "quote": "Er handelte mit dem Ziel, dass ihr Leichnam nicht gefunden würde.",
    "verdict": "Audiencia Provincial de Huelva (Tribunal del Jurado), Urteil Nr. 135/2021 vom 9. Dezember 2021: Prisión permanente revisable wegen Mordes, zusätzlich 17,5 Jahre Haft wegen Freiheitsberaubung in Tateinheit mit sexueller Nötigung",
    "status": "rechtskräftig seit 2022 (die Audiencia Provincial de Huelva bestätigte die Rechtskraft, nachdem keine der Parteien Berufung eingelegt hatte)",
  },
})

import io
io.open("w1_sued.json","w",encoding="utf-8").write(json.dumps(cases,ensure_ascii=False,indent=1))
print("w1_sued.json:",len(cases),"Fälle")
for c in cases:
    print("  •",c.get("id"),"|",c.get("title"),"|",c.get("land"),c.get("year"),
          "|",c.get("duration"),"| diff",c.get("difficulty"),
          "| Hinweise",len(c.get("clues",[])),"| Verd.",len(c.get("suspects",[])),
          "| Docs",len(c.get("docs",[])),"| Links",len(c.get("links",[])))
